name: Delete old container images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Testing the container deletion mechanism'

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete 'dev' containers older than a week
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ env.IMAGE_NAME }}
          cut-off: A week ago UTC
          account-type: org
          org-name: fails-components
          keep-at-least: 1
          untagged-only: true
          token: ${{ secrets.GITHUB_TOKEN }}


 