name: Delete old container images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Testing the container deletion mechanism'

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete image sha
	      uses: r26d/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: ghcr-delete-image-dummy
          token: ${{ secrets.GHCR_TOKEN}}
          tagged-keep-latest: 5
          untagged-keep-latest: 1
          tag-regex: sha-.
      - name: Delete image release candiate
	      uses: r26d/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: ghcr-delete-image-dummy
          token: ${{ secrets.GHCR_TOKEN}}
          tagged-keep-latest: 5
          untagged-keep-latest: 1
          tag-regex: \d\.\d.\d-rc\d


 